version: '3'
services:
  dash-frontend:
    image: tgalske/dash-frontend
    restart: always    
    networks:
      - dash-net
    ports:
      - "3000:80"
    labels:
      - "traefik.backend=dash-frontend"
      - "traefik.docker.network=dash-net"
      - "traefik.frontend.rule=PathPrefixStrip:/"
      - "traefik.enable=true"
      - "traefik.port=80"
networks:
  dash-net:
    external: true
